//! Bakes the octos mock's canned responses into `examples/automation/mock_octos.rs`.
//!
//! The bodies live as JSON files under `examples/automation/octos/`, listed by
//! `index.json`. Keeping them out of the Rust source means a new case is a file
//! plus one index entry — no Rust to edit, since the `canned` lookup is
//! generated from the index too.
//!
//! Every file is parsed here rather than at run time. A malformed body inside
//! the guest is close to invisible: the reply is silently skipped and the
//! client just waits, so the failure surfaces as a hang minutes later on a
//! different machine. Failing the build names the file and the parse error.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::{env, fs};

use serde_json::Value;

/// Directory holding `index.json` and the response bodies.
const DATA_DIR: &str = "examples/automation/octos";
/// Generated file, `include!`d by the example.
const GENERATED: &str = "octos_responses.rs";

fn main() {
    let data_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(DATA_DIR);
    // Cargo replaces the default "rerun on any change" with exactly what we
    // print, so the directory has to be listed as well as the files: without it
    // a NEW case would not trigger a rebuild and would silently not exist.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", data_dir.display());

    let index = read_json(&data_dir.join("index.json"));
    let captured = index
        .get("captured")
        .unwrap_or_else(|| fail("index.json: missing `captured`"));

    let mut out = String::from(
        "// @generated by build.rs from examples/automation/octos/. Do not edit.\n\
         // Edit the JSON files and the index there instead.\n",
    );

    for (field, name) in [
        ("session", "CAPTURED_SESSION"),
        ("profile", "CAPTURED_PROFILE"),
        ("turn", "CAPTURED_TURN"),
    ] {
        let value = captured
            .get(field)
            .and_then(Value::as_str)
            .unwrap_or_else(|| fail(&format!("index.json: `captured.{field}` must be a string")));
        out.push_str(&format!("const {name}: &str = {};\n", literal(value)));
    }

    let results = index
        .get("results")
        .and_then(Value::as_array)
        .unwrap_or_else(|| fail("index.json: `results` must be an array"));

    let mut arms = String::new();
    let mut seen_methods = BTreeSet::new();
    let mut seen_consts = BTreeSet::new();
    for entry in results {
        let method = field(entry, "method");
        let name = field(entry, "const");
        let file = field(entry, "file");
        // A duplicate method silently shadows the later arm; a duplicate const
        // is a redefinition the compiler would report against generated code,
        // which is a confusing place to read an error.
        if !seen_methods.insert(method.to_owned()) {
            fail(&format!("index.json: `{method}` listed twice"));
        }
        if !seen_consts.insert(name.to_owned()) {
            fail(&format!("index.json: const `{name}` used twice"));
        }

        let body = read_body(&data_dir.join(file), file);
        out.push_str(&format!("const {name}: &str = {};\n", literal(&body)));
        arms.push_str(&format!("        {} => Some({name}),\n", literal(method)));
    }

    out.push_str(
        "\n/// The recorded body for `method`, or None when the capture has no case for it.\n\
         fn canned(method: &str) -> Option<&'static str> {\n\
         \x20   match method {\n",
    );
    out.push_str(&arms);
    out.push_str("        _ => None,\n    }\n}\n");

    let stream = index
        .get("turn_stream")
        .unwrap_or_else(|| fail("index.json: missing `turn_stream`"));
    let stream_name = field(stream, "const");
    let stream_file = field(stream, "file");
    let stream_body = read_body(&data_dir.join(stream_file), stream_file);
    if !serde_json::from_str::<Value>(&stream_body)
        .expect("validated by read_body")
        .is_array()
    {
        fail(&format!("{stream_file}: turn stream must be a JSON array of envelopes"));
    }
    out.push_str(&format!(
        "const {stream_name}: &str = {};\n",
        literal(&stream_body)
    ));

    let path = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join(GENERATED);
    fs::write(&path, out).unwrap_or_else(|error| fail(&format!("writing {}: {error}", path.display())));
}

/// Read a response body, failing the build if it is not valid JSON.
fn read_body(path: &Path, name: &str) -> String {
    println!("cargo:rerun-if-changed={}", path.display());
    let body = fs::read_to_string(path)
        .unwrap_or_else(|error| fail(&format!("{name}: {error}")))
        .trim()
        .to_owned();
    if let Err(error) = serde_json::from_str::<Value>(&body) {
        fail(&format!("{name}: not valid JSON: {error}"));
    }
    body
}

fn read_json(path: &Path) -> Value {
    println!("cargo:rerun-if-changed={}", path.display());
    let text = fs::read_to_string(path)
        .unwrap_or_else(|error| fail(&format!("{}: {error}", path.display())));
    serde_json::from_str(&text)
        .unwrap_or_else(|error| fail(&format!("{}: not valid JSON: {error}", path.display())))
}

fn field<'a>(entry: &'a Value, key: &str) -> &'a str {
    entry
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or_else(|| fail(&format!("index.json: every entry needs a string `{key}`")))
}

/// A Rust string literal for `value`.
///
/// `{:?}` escapes quotes, backslashes and control characters while leaving
/// printable text (emoji included) alone, so the emitted literal round-trips to
/// exactly these bytes. A raw string would be shorter but is not safe to
/// generate: any `"#` in a body would end it early.
fn literal(value: &str) -> String {
    format!("{value:?}")
}

fn fail(message: &str) -> ! {
    // Emitted as a warning too: cargo prints these above the failure, where
    // they read as a plain sentence instead of a panic in generated-code land.
    println!("cargo:warning=mock_octos data: {message}");
    // Explicit argument, NOT `panic!("...{message}")`: this package is edition
    // 2018, where a single-argument panic! passes the string through unchanged
    // and would print the literal braces.
    panic!("{}", format!("mock_octos data: {message}"));
}
