//! A standalone octos UI Protocol server, replayed from a `tcp_fiddler` capture
//! of a TUI session. Nothing is proxied: the guest answers the client itself by
//! writing frames back down the local connection with the mock server's
//! `tcp_response` capability, so no octos server needs to be running.
//!
//! The capture pairs a request with whatever the server happened to send while
//! that request was in flight, so `MockData[i].request` does NOT identify the
//! reply next to it — index 2's `profile/llm/list` sits beside the answer to
//! `tui-1`'s `config/capabilities/list`. What pairs a reply with its question is
//! the JSON-RPC `id`, so the bodies below are keyed by method and the live id is
//! echoed back onto them.
//!
//! ## The remote port has not gone away, it has been defanged
//!
//! `PoolInit` resolves and dials the remote half of the port map, and the
//! goroutine that reads the client waits for that dial to land before its first
//! `Read` (`tcpproxy/pool.go`: "upstream never came up"). Point the map at a
//! dead port and the guest is never invoked at all. So the map keeps a remote
//! that is certain to accept — the mock server's own HTTP port — and simply
//! never writes to it: every payload returns "/continue", which is what tells
//! the host to forward nothing.
//!
//! ## Where the bodies live
//!
//! Not here. `examples/automation/octos/` holds one JSON file per recorded
//! reply plus `index.json` listing them, and `build.rs` bakes those in — the
//! `canned` lookup below is generated from the index, so a new case is a file
//! and an index entry with no Rust to edit. The build parses every file, so a
//! malformed body fails the build naming the file, rather than being skipped at
//! run time and surfacing as a client that hangs.
//!
//! ## What is answered
//!
//! The bodies in `canned` are replayed verbatim: they are the replies the
//! capture recorded, which is exactly the set small enough to fit one WebSocket
//! frame and so reach the guest decoded rather than forwarded as split bytes.
//!
//! Three more are served without a recorded body, because the capture could not
//! have one:
//!
//! - `session/open` — the real reply is ~55 KB and was forwarded unrecorded.
//!   `session_open_result` assembles `{"opened": …}` from `session/status/read`
//!   and `session/hydrate`, so every field still comes from captured data.
//! - `turn/start` — answered with `{"accepted": true}`, because a turn is
//!   delivered as pushed notifications rather than a result. `turn_stream`
//!   replays those, retargeted at the live turn_id and prompt.
//! - `launch/resolve` — answered `resume`, which is the only decision that
//!   explains what the client did next in the capture (open a session rather
//!   than prompt).
//! - `mcp/status/list` and `tool/status/list` — reported empty, which is what
//!   the capture's own `mcp_summary`, `tool_summary` and `mcp_servers` say the
//!   session had.
//!
//! Result shapes come from the protocol crate (`SessionOpenResult`,
//! `TurnStartResult`, `LaunchResolveResult`) and, for the two status lists,
//! from the client's own decode structs plus the server handlers that build
//! them — not guessed.
//!
//! Every method the capture never saw gets an explicit JSON-RPC error. With no
//! upstream to fall through to, silence is indistinguishable from a hang.
extern crate wapc_guest as guest;
use guest::prelude::*;
extern crate wasm_mock_util;
extern crate httparse;
extern crate serde_json;
use base64::{engine::general_purpose, Engine as _};
use bytes::BytesMut;
use lazy_static::lazy_static;
use serde_json::Value;
use std::collections::HashMap;
use std::sync::Mutex;
use tokio_util::codec::{Decoder, Encoder};
use wasm_mock_util::*;
use websocket_codec::{MessageCodec, Opcode};

/// Local port the TUI connects to, and a remote that exists only to satisfy the
/// proxy's dial. Both halves must match the registered function names, so they
/// come from one macro rather than three string literals.
macro_rules! port_map {
    () => {
        "3335-:20825"
    };
}
/// Also the `tcp_response` binding: the host selects the client connection with
/// `strings.Contains(key, portmap)`.
const PORT_MAP: &str = port_map!();

/// Per-connection framing state. The host hands us raw TCP payloads, so the
/// upgrade and the frame boundaries are ours to track.
struct Conn {
    upgraded: bool,
    buf: BytesMut,
    /// Decodes the client's masked frames.
    decoder: MessageCodec,
    /// Encodes our unmasked ones. A server must not mask, and reusing the
    /// request codec here would produce frames the client drops.
    encoder: MessageCodec,
}

impl Conn {
    fn new() -> Self {
        Conn {
            upgraded: false,
            buf: BytesMut::new(),
            decoder: MessageCodec::client(),
            encoder: MessageCodec::server(),
        }
    }
}

// Canned bodies, the captured session/profile/turn ids, and the `canned`
// lookup, generated by build.rs from examples/automation/octos/index.json.
include!(concat!(env!("OUT_DIR"), "/octos_responses.rs"));

lazy_static! {
    /// Keyed on "{Laddr}-{Raddr}", the same identity the host reports.
    static ref CHANNELS: Mutex<HashMap<String, Conn>> = Mutex::new(HashMap::new());
    /// session_id the live client is using, taken from request params.
    static ref SESSION: Mutex<String> = Mutex::new(String::new());
}

/// Point a canned body at the session the live client actually opened.
///
/// Two forms need swapping: request results carry the full `<profile>:<channel>
/// :<chat>#<topic>` key, while `projection/envelope` splits it into `session_id`
/// without the topic plus a separate `topic` field. Replacing the long form
/// first leaves only genuine base-form occurrences for the second pass.
fn retarget(body: &str) -> String {
    let session = SESSION.lock().unwrap();
    if session.is_empty() || *session == CAPTURED_SESSION {
        return body.to_string();
    }
    let captured_base = CAPTURED_SESSION.split('#').next().unwrap_or(CAPTURED_SESSION);
    let live_base = session.split('#').next().unwrap_or(&session);
    body.replace(CAPTURED_SESSION, &session)
        .replace(captured_base, live_base)
}

/// `session/open` returns `{"opened": SessionOpened}`. The capture never
/// recorded one — the reply is ~55 KB and the fiddler forwarded it as split
/// bytes without decoding — so it is assembled from the pieces that WERE
/// captured, every one of them lifted from `session/status/read` or
/// `session/hydrate` rather than invented.
fn session_open_result() -> Option<Value> {
    let capabilities: Value = serde_json::from_str(&retarget(CAPABILITIES)).ok()?;
    let status: Value = serde_json::from_str(&retarget(SESSION_STATUS_READ)).ok()?;
    let hydrate: Value = serde_json::from_str(&retarget(SESSION_HYDRATE)).ok()?;
    Some(serde_json::json!({"opened": {
        "session_id": status["session_id"],
        "active_profile_id": status["profile_id"],
        "workspace_root": status["runtime_policy_stamp"]["workspace_root"],
        "context": status["context"],
        "context_state": status["context_state"],
        "cursor": hydrate["cursor"],
        "capabilities": capabilities["capabilities"],
    }}))
}

/// The profile a request is scoped to, falling back to the captured one.
fn profile_of(params: &Value) -> String {
    params
        .get("profile_id")
        .and_then(Value::as_str)
        .unwrap_or(CAPTURED_PROFILE)
        .to_string()
}

/// The session to stamp on a reply: whichever one the client is using, or the
/// captured one until it has told us. Takes and releases the lock, because
/// callers go on to `retarget`, which takes it again.
fn live_session() -> String {
    let session = SESSION.lock().unwrap();
    if session.is_empty() {
        CAPTURED_SESSION.to_string()
    } else {
        session.clone()
    }
}

/// The result body for `method`, or None when nothing was captured.
fn result_for(method: &str, params: &Value) -> Option<Value> {
    match method {
        //`turn/start` is acknowledged, not answered: the turn itself arrives as
        //the notification stream that `turn_stream` replays.
        "turn/start" => Some(serde_json::json!({"accepted": true})),
        "session/open" => session_open_result(),
        //The capture recorded no body, but the client's next move gives the
        //decision away: it went straight to `session/open` on
        //"alan:local:tui#coding" rather than prompting. Only `resume` does
        //that, and the client builds that id out of `resolved_profile`
        //(`open_resolved_launch_session`) — so echoing the profile the client
        //asked for is what keeps the session it opens consistent with the one
        //the canned bodies are retargeted to. `existing_profiles` belongs to
        //`cross_profile` and is omitted.
        "launch/resolve" => Some(serde_json::json!({
            "decision": "resume",
            "resolved_profile": profile_of(params),
        })),
        //Neither was captured, but the capture still fixes every value: the
        //session had `mcp_summary {0,0,0,0}` and `runtime_policy_stamp
        //.mcp_servers []`, so there are no servers to report.
        "mcp/status/list" => Some(serde_json::json!({
            "profile_id": profile_of(params),
            "session_id": live_session(),
            "servers": [],
            "summary": {"connected": 0, "connecting": 0, "failed": 0, "disabled": 0},
        })),
        //Likewise `tool_summary {visible 0, enabled 0, denied 0, policy_id
        //"profile"}`. The server builds `tools` by filtering its spec table to
        //names that are visible or disabled, and both sets were empty here —
        //this session defers everything behind `dynamic_tool_discovery`, and
        //deferred names are deliberately not listed.
        //
        //`coding_tool_contract` is omitted. The client types it `Option`, so
        //absence is benign, whereas its contents derive entirely from
        //server-side registry state the capture never exposed: synthesising it
        //from an empty toolset would mark every required tool missing and
        //report `status: "incomplete"`, i.e. claim a broken session.
        "tool/status/list" => Some(serde_json::json!({
            "profile_id": profile_of(params),
            "session_id": live_session(),
            "policy_id": "profile",
            "tools": [],
        })),
        _ => serde_json::from_str(&retarget(canned(method)?)).ok(),
    }
}

/// The pushed notifications a turn produces, retargeted at the live session,
/// turn and prompt.
///
/// The client tracks envelope `seq` and reports gaps as `protocol/replay_lossy`,
/// so these are renumbered contiguously: the capture is missing seven deltas
/// (the fiddler forwards payloads it cannot frame-align without recording them),
/// and replaying its original numbering would look like loss on every turn. The
/// text those deltas carried is gone, so the streamed reasoning reads slightly
/// clipped — `assistant_persisted` still carries the complete final answer,
/// which is what the client keeps.
fn turn_stream(turn_id: &str, prompt: &str) -> Vec<Value> {
    let raw = retarget(TURN_STREAM).replace(CAPTURED_TURN, turn_id);
    let mut envelopes: Vec<Value> = match serde_json::from_str(&raw) {
        Ok(envelopes) => envelopes,
        Err(_) => return vec![],
    };
    for envelope in &mut envelopes {
        if envelope.pointer("/params/payload/type").and_then(Value::as_str) == Some("user_message") {
            if let Some(text) = envelope.pointer_mut("/params/payload/data/text") {
                *text = Value::String(prompt.to_string());
            }
        }
    }
    envelopes
}

/// Concatenate the text parts of a `turn/start` `input` array.
fn prompt_of(params: &Value) -> String {
    params
        .get("input")
        .and_then(Value::as_array)
        .map(|parts| {
            parts
                .iter()
                .filter_map(|part| part.get("text").and_then(Value::as_str))
                .collect::<Vec<_>>()
                .join("")
        })
        .unwrap_or_default()
}

/// Every frame to send back for one client frame: the reply first, then any
/// notifications that request sets off. Empty when the frame is not a JSON-RPC
/// request — a client notification has no id and expects no answer.
fn replies_to(text: &str) -> Vec<String> {
    let v: Value = match serde_json::from_str(text) {
        Ok(v) => v,
        Err(_) => return vec![],
    };
    let method = match v.get("method").and_then(Value::as_str) {
        Some(method) => method.to_string(),
        None => return vec![],
    };
    if let Some(session) = v.pointer("/params/session_id").and_then(Value::as_str) {
        *SESSION.lock().unwrap() = session.to_string();
    }
    let id = match v.get("id") {
        Some(id) => id,
        None => return vec![],
    };

    let params = v.get("params").cloned().unwrap_or(Value::Null);
    let mut out = vec![match result_for(&method, &params) {
        Some(result) => serde_json::json!({"jsonrpc": "2.0", "id": id, "result": result}),
        //Answering is not optional now that nothing sits behind this guest: a
        //silent drop looks identical to a hung server, and the TUI waits on the
        //id forever. Name the method so the gap is obvious in the client's own
        //error surface.
        None => serde_json::json!({
            "jsonrpc": "2.0",
            "id": id,
            "error": {
                "code": -32000,
                "message": format!("mock_octos: no response captured for {}", method),
            }
        }),
    }
    .to_string()];

    if method == "turn/start" {
        let turn_id = params.get("turn_id").and_then(Value::as_str).unwrap_or(CAPTURED_TURN);
        out.extend(
            turn_stream(turn_id, &prompt_of(&params))
                .iter()
                .map(Value::to_string),
        );
    }
    out
}

/// The 101 the real server would have sent. `Sec-WebSocket-Accept` is derived
/// from the client's key, so this cannot be a canned string.
fn handshake_response(raw: &[u8]) -> Option<String> {
    let mut headers = [httparse::EMPTY_HEADER; 64];
    let mut request = httparse::Request::new(&mut headers);
    if !request.parse(raw).ok()?.is_complete() {
        return None;
    }
    let lookup = |name: &'static str| -> Option<&str> {
        request
            .headers
            .iter()
            .find(|header| header.name.eq_ignore_ascii_case(name))
            .and_then(|header| std::str::from_utf8(header.value).ok())
    };
    let accept = websocket_codec::ClientRequest::parse(lookup).ok()?.ws_accept();
    Some(format!(
        "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: {}\r\n\r\n",
        accept
    ))
}

/// Write frames back down the client's own connection.
///
/// `TcpResponse` (`tcpproxy/pool.go`) picks the local connection by
/// `strings.Contains(key, portmap)` and then `lconn.RemoteAddr() == req.Laddr`,
/// so the binding must be the port map and `Laddr` must be the address the host
/// handed us — an empty `Laddr` broadcasts to every client on the port.
///
/// Called through `host_call` rather than `foo_tcp_response!`: the host decodes
/// this payload as a msgpack ARRAY of `TcpReq` and answers with zero bytes,
/// while the macro serialises a single struct and then tries to parse a
/// `TcpReq` back out of the empty reply.
fn send_to_client(items: Vec<TcpReq>) -> Result<(), Box<dyn std::error::Error + Sync + Send>> {
    if items.is_empty() {
        return Ok(());
    }
    let buf = rmp_serde::to_vec(&items)?;
    host_call(PORT_MAP, "foo", "tcp_response", &buf)?;
    Ok(())
}

fn frame_item(payload: Vec<u8>, description: String, laddr: &str, raddr: &str) -> TcpReq {
    TcpReq {
        Payload: general_purpose::STANDARD.encode(payload),
        String: description,
        Index: 0,
        //A non-empty Id makes the host treat this as an RPC awaiting a matching
        //reply from a remote that no longer exists.
        Id: String::new(),
        Command: String::new(),
        ReportType: String::from("Mock"),
        Timeout: false,
        Laddr: laddr.to_string(),
        Raddr: raddr.to_string(),
    }
}

/// Everything the client sends is answered here; nothing is ever forwarded.
fn _req(msg: &[u8]) -> CallResult {
    let tcp_payload: TcpPayload = rmp_serde::from_read_ref(msg)?;
    let payload = general_purpose::STANDARD.decode(tcp_payload.Payload.clone())?;
    let conn = format!("{}-{}", tcp_payload.Laddr, tcp_payload.Raddr);
    let mut channels = CHANNELS.lock().unwrap();
    let channel = channels.entry(conn).or_insert_with(Conn::new);

    //A payload opening with a request line is a fresh connection: the OS reuses
    //ephemeral ports, so without re-arming, a new client inherits a channel
    //already past its handshake and its upgrade is fed to the frame decoder.
    if payload.starts_with(b"GET ") {
        *channel = Conn::new();
        let items = match handshake_response(&payload) {
            Some(response) => vec![frame_item(
                response.clone().into_bytes(),
                response,
                &tcp_payload.Laddr,
                &tcp_payload.Raddr,
            )],
            //Header split across TCP reads: wait for the rest rather than
            //answering a handshake we have not finished reading.
            None => return Ok(b"/continue".to_vec()),
        };
        channel.upgraded = true;
        drop(channels);
        send_to_client(items)?;
        return Ok(b"/continue".to_vec());
    }
    if !channel.upgraded {
        return Ok(b"/continue".to_vec());
    }

    channel.buf.extend_from_slice(&payload);
    let mut items = vec![];
    //Drain every complete frame: one TCP read routinely carries several, and
    //answering only the first strands the rest of the client's requests.
    //`decode` consumes nothing on a partial frame, so a split tail simply stays
    //buffered for the next payload.
    while let Ok(Some(message)) = channel.decoder.decode(&mut channel.buf) {
        //One request can produce many frames: a turn is a reply followed by the
        //whole notification stream.
        let outgoing: Vec<websocket_codec::Message> = match message.opcode() {
            //Text is the only opcode carrying JSON-RPC.
            Opcode::Text => message
                .as_text()
                .map(replies_to)
                .unwrap_or_default()
                .into_iter()
                .map(websocket_codec::Message::text)
                .collect(),
            //Nothing upstream is going to keep this connection alive any more.
            Opcode::Ping => vec![websocket_codec::Message::pong(message.data().clone())],
            Opcode::Close => vec![websocket_codec::Message::close()],
            _ => continue,
        };
        for frame in outgoing {
            let mut encoded = BytesMut::new();
            if channel.encoder.encode(frame.clone(), &mut encoded).is_err() {
                continue;
            }
            items.push(frame_item(
                encoded.to_vec(),
                frame.as_text().unwrap_or_default().to_string(),
                &tcp_payload.Laddr,
                &tcp_payload.Raddr,
            ));
        }
    }
    drop(channels);
    send_to_client(items)?;
    //Never forward: "/continue" is what tells the host to write nothing to the
    //remote (`if !bytes.Equal(mb, "/continue")` in tcpproxy/pool.go).
    Ok(b"/continue".to_vec())
}

/// The remote is a placeholder that is never written to, so this only ever
/// fires if something else answers on that port. Drop it either way.
fn _res(_msg: &[u8]) -> CallResult {
    Ok(b"/continue".to_vec())
}

#[no_mangle]
pub extern "C" fn _start() {
    register_function(concat!(port_map!(), "_tcp_modify_req"), _req);
    register_function(concat!(port_map!(), "_tcp_modify_res"), _res);
}

fn main() {}

#[cfg(test)]
mod tests {
    use super::*;

    lazy_static! {
        static ref TEST_LOCK: Mutex<()> = Mutex::new(());
    }

    /// SESSION is process-wide, exactly as it is in the guest, so the tests take
    /// turns rather than racing each other's state.
    fn reset() -> std::sync::MutexGuard<'static, ()> {
        let guard = TEST_LOCK.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
        CHANNELS.lock().unwrap().clear();
        SESSION.lock().unwrap().clear();
        guard
    }

    /// The single reply to a request that produces no notifications.
    fn reply(request: &str) -> Value {
        let frames = replies_to(request);
        assert_eq!(frames.len(), 1, "expected exactly one frame");
        serde_json::from_str(&frames[0]).expect("valid json")
    }

    fn frames(request: &str) -> Vec<Value> {
        replies_to(request)
            .iter()
            .map(|frame| serde_json::from_str(frame).expect("valid json"))
            .collect()
    }

    /// Every captured method answers from its own recorded body. The capture
    /// pairs a reply with whatever request was in flight rather than the one it
    /// answers, so this is keyed on the method, never on that adjacency.
    #[test]
    fn answers_each_captured_method_from_its_own_body() {
        let _guard = reset();
        assert!(reply(r#"{"jsonrpc":"2.0","id":1,"method":"config/capabilities/list","params":{}}"#)
            ["result"]["capabilities"]
            .is_object());
        assert_eq!(
            reply(r#"{"jsonrpc":"2.0","id":2,"method":"profile/llm/list","params":{}}"#)["result"]["primary"]
                ["model"],
            "deepseek-v4-pro"
        );
        assert_eq!(
            reply(r#"{"jsonrpc":"2.0","id":3,"method":"loop/list","params":{}}"#)["result"]["loops"]
                .as_array()
                .expect("loops")
                .len(),
            2
        );
        assert_eq!(
            reply(r#"{"jsonrpc":"2.0","id":4,"method":"session/hydrate","params":{}}"#)["result"]["messages"]
                .as_array()
                .expect("messages")
                .len(),
            30
        );
    }

    /// The id is echoed verbatim — the client matches replies on it — and it is
    /// the live one, not the `tui-N` the capture happened to use.
    #[test]
    fn echoes_the_live_id() {
        let _guard = reset();
        let answer = reply(r#"{"jsonrpc":"2.0","id":"tui-99","method":"agent/list","params":{}}"#);
        assert_eq!(answer["id"], "tui-99");
        assert_eq!(answer["jsonrpc"], "2.0");
    }

    /// With no upstream, dropping an uncaptured method is indistinguishable
    /// from a hung server: the client waits on that id forever.
    #[test]
    fn errors_rather_than_hanging_on_an_uncaptured_method() {
        let _guard = reset();
        let answer = reply(r#"{"jsonrpc":"2.0","id":7,"method":"snapshot/list","params":{}}"#);
        assert!(answer.get("result").is_none());
        assert_eq!(answer["error"]["code"], -32000);
        assert!(answer["error"]["message"].as_str().expect("message").contains("snapshot/list"));
    }

    /// The client decodes into `McpStatusListResult` / `ToolStatusListResult`
    /// and turns any decode failure into a visible app error, so the shapes
    /// matter more than the contents. `session_id` is the one required member
    /// of each.
    #[test]
    fn reports_an_empty_mcp_and_tool_surface_for_the_live_session() {
        let _guard = reset();
        let session = r#"{"session_id":"bob:local:tui#coding","profile_id":"bob"}"#;
        let mcp = reply(&format!(
            r#"{{"jsonrpc":"2.0","id":1,"method":"mcp/status/list","params":{}}}"#,
            session
        ))["result"]
            .clone();
        assert_eq!(mcp["session_id"], "bob:local:tui#coding");
        assert_eq!(mcp["profile_id"], "bob");
        assert_eq!(mcp["servers"].as_array().expect("servers").len(), 0);
        // Corroborated by mcp_summary in the captured session/status/read.
        assert_eq!(mcp["summary"], serde_json::json!({"connected":0,"connecting":0,"failed":0,"disabled":0}));

        let tools = reply(&format!(
            r#"{{"jsonrpc":"2.0","id":2,"method":"tool/status/list","params":{}}}"#,
            session
        ))["result"]
            .clone();
        assert_eq!(tools["session_id"], "bob:local:tui#coding");
        // Corroborated by tool_summary.policy_id in the same capture.
        assert_eq!(tools["policy_id"], "profile");
        assert_eq!(tools["tools"].as_array().expect("tools").len(), 0);
        assert!(
            tools.get("coding_tool_contract").is_none(),
            "an invented contract would report the session broken"
        );
    }

    /// Only `resume` sends the client straight to `session/open`; the other
    /// three decisions open a prompt menu or bounce it to onboarding, which is
    /// not what the capture shows happening next.
    #[test]
    fn resolves_launch_to_resume() {
        let _guard = reset();
        let result = reply(
            r#"{"jsonrpc":"2.0","id":3,"method":"launch/resolve","params":{"cwd":"/tmp/x","profile_id":"alan"}}"#,
        )["result"]
            .clone();
        assert_eq!(result["decision"], "resume");
        assert_eq!(result["resolved_profile"], "alan");
        assert!(result.get("existing_profiles").is_none(), "cross_profile only");
    }

    /// The client derives its session id from `resolved_profile`
    /// (`open_resolved_launch_session`), so echoing back a different profile
    /// than the one asked for would send it to open a session the canned
    /// bodies are not keyed to.
    #[test]
    fn echoes_the_requested_profile_and_falls_back_to_the_captured_one() {
        let _guard = reset();
        assert_eq!(
            reply(r#"{"jsonrpc":"2.0","id":3,"method":"launch/resolve","params":{"cwd":"/tmp/x","profile_id":"bob"}}"#)
                ["result"]["resolved_profile"],
            "bob"
        );
        assert_eq!(
            reply(r#"{"jsonrpc":"2.0","id":3,"method":"launch/resolve","params":{"cwd":"/tmp/x"}}"#)["result"]
                ["resolved_profile"],
            CAPTURED_PROFILE
        );
    }

    /// `session/open` returns `{"opened": SessionOpened}`; `session_id` is the
    /// only member the client requires, but an empty shell would leave it with
    /// no cursor to resume from and no negotiated capabilities.
    #[test]
    fn opens_a_session_with_the_pieces_the_capture_did_record() {
        let _guard = reset();
        let opened = reply(
            r#"{"jsonrpc":"2.0","id":4,"method":"session/open","params":{"session_id":"bob:local:tui#coding"}}"#,
        )["result"]["opened"]
            .clone();
        assert_eq!(opened["session_id"], "bob:local:tui#coding");
        assert_eq!(opened["active_profile_id"], "alan");
        assert_eq!(opened["cursor"]["seq"], 1613);
        assert_eq!(opened["context_state"]["recovery_state"], "exact");
        assert_eq!(
            opened["capabilities"]["supported_methods"].as_array().expect("methods").len(),
            67
        );
        assert!(opened["workspace_root"].is_string());
    }

    /// A turn is an ack plus the whole notification stream. The client keys
    /// every envelope on its own turn_id, so replaying the captured one would
    /// have the TUI discard the lot.
    #[test]
    fn replays_a_turn_against_the_live_turn_id_and_prompt() {
        let _guard = reset();
        let frames = frames(
            r#"{"jsonrpc":"2.0","id":14,"method":"turn/start","params":{"session_id":"bob:local:tui#coding","turn_id":"live-turn-1","input":[{"kind":"text","text":"how are you"}]}}"#,
        );
        assert_eq!(frames[0]["result"]["accepted"], true);
        assert!(frames.len() > 40, "got {} frames", frames.len());

        let joined = serde_json::to_string(&frames).expect("json");
        assert!(!joined.contains(CAPTURED_TURN), "captured turn id leaked");
        assert!(!joined.contains(CAPTURED_SESSION), "captured session id leaked");

        let payloads: Vec<&str> = frames
            .iter()
            .filter_map(|frame| frame.pointer("/params/payload/type").and_then(Value::as_str))
            .collect();
        assert!(payloads.contains(&"reasoning_delta"));
        assert!(payloads.contains(&"assistant_delta"));
        assert_eq!(payloads.last(), Some(&"turn_terminal"), "the turn must end terminally");

        // The prompt is the user's, not the captured "hello".
        let echoed = frames
            .iter()
            .find(|frame| frame.pointer("/params/payload/type").and_then(Value::as_str) == Some("user_message"))
            .expect("user_message");
        assert_eq!(echoed["params"]["payload"]["data"]["text"], "how are you");
    }

    /// The client reports gaps in envelope seq as replay loss, and the capture
    /// is missing seven deltas, so the stream is renumbered contiguously.
    #[test]
    fn numbers_envelope_seqs_without_gaps() {
        let _guard = reset();
        let frames = frames(
            r#"{"jsonrpc":"2.0","id":14,"method":"turn/start","params":{"turn_id":"live-turn-1","input":[]}}"#,
        );
        let seqs: Vec<u64> = frames
            .iter()
            .filter_map(|frame| frame.pointer("/params/seq").and_then(Value::as_u64))
            .collect();
        assert!(!seqs.is_empty());
        assert_eq!(seqs, (1..=seqs.len() as u64).collect::<Vec<_>>());
    }

    /// The final answer is what the client keeps once the deltas stop, so it
    /// has to be the complete sentence even though some deltas were not
    /// captured.
    #[test]
    fn persists_the_complete_answer_even_though_deltas_are_lossy() {
        let _guard = reset();
        let frames = frames(
            r#"{"jsonrpc":"2.0","id":14,"method":"turn/start","params":{"turn_id":"t","input":[]}}"#,
        );
        let persisted = frames
            .iter()
            .find(|frame| {
                frame.pointer("/params/payload/type").and_then(Value::as_str) == Some("assistant_persisted")
            })
            .expect("assistant_persisted");
        assert_eq!(
            persisted["params"]["payload"]["data"]["text"],
            "Tello! \u{1F60A} Still here. Anything you'd like to do today?"
        );
    }

    /// A client notification carries no id and expects no answer; replying to
    /// one would put an unsolicited frame on the wire.
    #[test]
    fn stays_quiet_for_notifications() {
        let _guard = reset();
        assert!(replies_to(r#"{"jsonrpc":"2.0","method":"turn/interrupt","params":{}}"#).is_empty());
    }

    /// Canned bodies embed the captured session in dozens of places, including
    /// every message_id.
    #[test]
    fn retargets_canned_bodies_at_the_live_session() {
        let _guard = reset();
        let answer = reply(
            r#"{"jsonrpc":"2.0","id":6,"method":"session/hydrate","params":{"session_id":"bob:local:tui#coding"}}"#,
        );
        assert_eq!(answer["result"]["session_id"], "bob:local:tui#coding");
        assert!(
            !serde_json::to_string(&answer).unwrap().contains(CAPTURED_SESSION),
            "no captured session id survives retargeting"
        );
    }

    /// The accept value is derived from the client's key, so a canned 101 would
    /// be rejected by any conforming client.
    #[test]
    fn derives_the_handshake_accept_from_the_clients_key() {
        let _guard = reset();
        let request = b"GET /api/ui-protocol/ws HTTP/1.1\r\nHost: 127.0.0.1:3335\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: wThjiiUQ0W/uJEO+1cCujA==\r\n\r\n";
        let response = handshake_response(request).expect("handshake");
        assert!(response.starts_with("HTTP/1.1 101 Switching Protocols\r\n"));
        // base64(sha1("wThjiiUQ0W/uJEO+1cCujA==" + RFC6455 GUID))
        assert!(
            response.contains("Sec-WebSocket-Accept: EiOE8cESg3a8QQmX8+xmdGXFu6k="),
            "got {}",
            response
        );
    }

    /// A truncated header must not be answered: the accept value would be
    /// computed from a key that has not fully arrived.
    #[test]
    fn waits_for_a_handshake_split_across_reads() {
        let _guard = reset();
        assert!(handshake_response(b"GET /api/ui-protocol/ws HTTP/1.1\r\nHost: 127.0.0.1").is_none());
    }

    /// Client frames are masked and server frames are not; encoding a reply
    /// with the request codec would produce a frame the client discards.
    #[test]
    fn replies_with_unmasked_frames_that_round_trip() {
        let _guard = reset();
        let mut client = MessageCodec::client();
        let mut request = BytesMut::new();
        client
            .encode(
                websocket_codec::Message::text(
                    r#"{"jsonrpc":"2.0","id":"tui-1","method":"agent/list","params":{}}"#,
                ),
                &mut request,
            )
            .expect("encodes");
        assert!(request[1] & 0x80 != 0, "client frames are masked");

        let mut conn = Conn::new();
        conn.buf.extend_from_slice(&request);
        let message = conn.decoder.decode(&mut conn.buf).expect("decodes").expect("a frame");
        let answer = replies_to(message.as_text().expect("text")).remove(0);

        let mut encoded = BytesMut::new();
        conn.encoder
            .encode(websocket_codec::Message::text(answer), &mut encoded)
            .expect("encodes");
        assert!(encoded[1] & 0x80 == 0, "server frames are not masked");

        let decoded = MessageCodec::server()
            .decode(&mut encoded)
            .expect("decodes")
            .expect("a frame");
        let value: Value = serde_json::from_str(decoded.as_text().expect("text")).expect("json");
        assert_eq!(value["id"], "tui-1");
        assert_eq!(value["result"]["agents"].as_array().expect("agents").len(), 0);
    }
}
